// <auto-generated />
namespace TravelExperience.DataAccess.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<< HEAD:TravelExperience.DataAccess/Persistence/Migrations/202111291644254_Initial.Designer.cs
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202111291644254_Initial"; }
=======
    public sealed partial class NewAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202111271056169_NewAdd"; }
>>>>>>> 5a609f1fe7596605d05089412c86f8576ff9485c:TravelExperience.DataAccess/Persistence/Migrations/202111271056169_NewAdd.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
